Repository DUNE-DAQ/trigger, pull requests merged in 2024-03, with the labels that each got.

#276 Updated AlgorithmPlugins Unit Test.
  unittest/AlgorithmPlugins_test.cxx
Labels: maintenance, miscellaneous deliverable

#272 New replay app
  python/trigger/replay_tps/README.md
  python/trigger/replay_tps/__main__.py
  python/trigger/replay_tps/doc/1_replay.png
  python/trigger/replay_tps/doc/1_system.png
  python/trigger/replay_tps/doc/1_system_no_frag_prod_connection.png
  python/trigger/replay_tps/doc/1_trigger.png
  python/trigger/replay_tps/doc/replay.png
  python/trigger/replay_tps/doc/system.png
  python/trigger/replay_tps/doc/system_no_frag_prod_connection.png
  python/trigger/replay_tps/doc/trigger.png
  python/trigger/replay_tps/replay_tp_app.py
Labels: miscellaneous deliverable

#273 Changing trigger type in trigger decision (message)
  plugins/ModuleLevelTrigger.cpp
Labels: miscellaneous deliverable

#284 Asztuc/max time over threshold
  plugins/TPChannelFilter.cpp
  python/trigger/test_channel_filter/test_channel_filter.py
  python/trigger/test_channel_filter/toplevel.py
  schema/trigger/tpchannelfilter.jsonnet
Labels: miscellaneous deliverable

#286 Fix for MLT deadtime, it now sets to kLive when DFO is "unbusy"
  plugins/ModuleLevelTrigger.cpp
Labels: miscellaneous deliverable

#285 Logging system rework
  include/trigger/Logging.hpp
  include/trigger/Tee.hxx
  plugins/CustomTriggerCandidateMaker.cpp
  plugins/FakeTPCreatorHeartbeatMaker.cpp
  plugins/ModuleLevelTrigger.cpp
  plugins/RandomTriggerCandidateMaker.cpp
  plugins/TABuffer.cpp
  plugins/TCBuffer.cpp
  plugins/TPBuffer.cpp
  plugins/TPChannelFilter.cpp
  plugins/TPSetBufferCreator.cpp
  plugins/TimingTriggerCandidateMaker.cpp
  plugins/TriggerPrimitiveMaker.cpp
  plugins/TriggerZipper.hpp
  src/LivetimeCounter.cpp
  src/TokenManager.cpp
  src/trigger/TimeSliceOutputBuffer.hpp
  src/trigger/TriggerGenericMaker.hpp
  test/plugins/TASetSink.cpp
  test/plugins/TPSetSink.cpp
Labels: miscellaneous deliverable

#288 CTB: Trigger integration
  CMakeLists.txt
  include/trigger/Issues.hpp
  plugins/CTBTriggerCandidateMaker.cpp
  plugins/CTBTriggerCandidateMaker.hpp
  plugins/ModuleLevelTrigger.cpp
  plugins/ModuleLevelTrigger.hpp
  schema/trigger/ctbtriggercandidatemaker.jsonnet
  schema/trigger/ctbtriggercandidatemakerinfo.jsonnet
Labels: miscellaneous deliverable

#287 Asztuc/trigger neutron source
  include/trigger/Issues.hpp
  plugins/ModuleLevelTrigger.cpp
  plugins/ModuleLevelTrigger.hpp
  plugins/TimingTriggerCandidateMaker.cpp
  plugins/TimingTriggerCandidateMaker.hpp
  python/trigger/replay_tp_to_chain/__main__.py
  schema/trigger/moduleleveltrigger.jsonnet
  schema/trigger/timingtriggercandidatemaker.jsonnet
Labels: miscellaneous deliverable

#289 Fixed compiler error in Issues.hpp and cleaned up a couple of typos t…
  include/trigger/Issues.hpp
Labels: miscellaneous deliverable

#290 Replay fix to (not) use CTB & fake HSI
  python/trigger/replay_tps/__main__.py
Labels: miscellaneous deliverable

#291 Updating to v1.8.0.
  CMakeLists.txt
Labels: maintenance
