Repository DUNE-DAQ/trigger, pull requests merged in 2024-04, with the labels that each got.

#292 Removed Separate Fragment Time Comparisons
  plugins/TriggerPrimitiveMaker.cpp
Labels: maintenance

#294 Fake hsi split
  python/trigger/replay_tps/__main__.py
Labels: miscellaneous deliverable

#295 Add support for CIB
  CMakeLists.txt
  include/trigger/Issues.hpp
  plugins/CIBTriggerCandidateMaker.cpp
  plugins/CIBTriggerCandidateMaker.hpp
  schema/trigger/cibtriggercandidatemaker.jsonnet
  schema/trigger/cibtriggercandidatemakerinfo.jsonnet
Labels: enhancement, miscellaneous deliverable

#299 Asztuc/tpwrapper fix
  plugins/TPBuffer.hpp
  python/trigger/replay_tps/__main__.py
Labels: miscellaneous deliverable
